---
deployment:
  tasks:
    - export DEPLOYPATH=/home/faocaksb/public_html/
    - export DEPLOYPATHDIST=/home/faocaksb/public_html/dist/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp dist/build.js $DEPLOYPATHDIST
    - /bin/cp dist/build.js.map $DEPLOYPATHDIST
